// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSR_UKEdhV9AhfVOXVKGX1OaNi2urhOU',
    appId: '1:617101945828:web:adc6b7d7d5836e49cc75f1',
    messagingSenderId: '617101945828',
    projectId: 'intermittent-fasting-b72f4',
    authDomain: 'intermittent-fasting-b72f4.firebaseapp.com',
    databaseURL: 'https://intermittent-fasting-b72f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intermittent-fasting-b72f4.appspot.com',
    measurementId: 'G-JR3B3JVCWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-h_uL9rYKwEjFnyiuD0UX37JbnkDu0ko',
    appId: '1:617101945828:android:15975fb9aa29f57acc75f1',
    messagingSenderId: '617101945828',
    projectId: 'intermittent-fasting-b72f4',
    databaseURL: 'https://intermittent-fasting-b72f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intermittent-fasting-b72f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Wl3CqGl-CcqyC5tOSgy5mhyr8HEIbXE',
    appId: '1:617101945828:ios:f4e2d5d4aa1545d1cc75f1',
    messagingSenderId: '617101945828',
    projectId: 'intermittent-fasting-b72f4',
    databaseURL: 'https://intermittent-fasting-b72f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intermittent-fasting-b72f4.appspot.com',
    iosClientId: '617101945828-iq9qkcgg8sf7ei4do8hn027dj2hh1g84.apps.googleusercontent.com',
    iosBundleId: 'com.mirimhee.intermittentfasting.intermittentFasting',
  );
}
